#!/bin/bash

# Find all files in the directory, if it doesn't match one of the
# patterns and it's a text file, add its name to the .filelist file.

# ignore uninteresting directories
find -type f | perl -wln -e '(m:/.git/:
or /.d$/
or /svn/
or /cvsignore/
or /flags/
)
or (-T and print);' > .gruf.filelist

#
# Perform additional trimming to filelist here.
#
#sed -i /"windows/"/d .filelist
